spring:
  application:
    name: SpringEssentialGuide

  # jdbc를 사용한다면 url을 jdbc-url로 작성
  datasource-meta:
    jdbc-url: jdbc:mysql://localhost:3306/firstDB?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${MetaDB_Username}
    password: ${MetaDB_Password}
    driver-class-name: com.mysql.cj.jdbc.Driver


  datasource-data:
    jdbc-url: jdbc:mysql://localhost:3306/secondDB?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${DataDB_Username}
    password: ${DataDB_Password}
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true

  # false 스프링 배치는 1개의 배치 작업에 대해 프로젝트를 실행하면 자동으로 배치 작업이 가동되기 때문에 해당 과정을 막아야 한다.
  batch:
    job:
      enabled: false
    # 메타데이터 테이블 생성 설정
    jdbc:
      initialize-schema: always
      schema: classpath:org/springframework/batch/core/schema-mysql.sql
