spring:
  application:
    name: SpringEssentialGuide
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 12341234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
        show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQLDialect