server:
  port: 8080
spring:
  application:
    name: SpringEssentialGuide
  datasource:
    url: jdbc:mysql://localhost:3306
    username: root
    password: 11111111
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        ddl-auto: create
        dialect: org.hibernate.dialect.MySQLDialect
      show-sql: true